package com.veilreader.app.data.manga

import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import androidx.room.withTransaction
import com.veilreader.app.data.BookImportResult
import com.veilreader.app.data.LocalLibraryRepository
import com.veilreader.app.data.db.MangaChapterEntity
import com.veilreader.app.data.db.MangaChapterSourceEntity
import com.veilreader.app.data.db.MangaSourceLinkEntity
import com.veilreader.app.data.db.VeilDatabase
import com.veilreader.app.domain.Book
import com.veilreader.app.domain.BookFormat
import com.veilreader.app.manga.importing.MangaCbzImportLimits
import com.veilreader.app.manga.importing.MangaCbzImportResult
import com.veilreader.app.manga.importing.MangaCbzIngestor
import com.veilreader.app.manga.library.CanonicalMangaId
import com.veilreader.app.manga.library.MangaCacheLayout
import com.veilreader.app.manga.library.MangaChapterAnchor
import com.veilreader.app.manga.library.MangaOfflineChapterLocator
import java.io.File
import java.io.IOException
import java.security.MessageDigest
import java.util.Locale
import java.util.UUID
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class LocalMangaImportCoordinator(
    context: Context,
    private val library: LocalLibraryRepository,
    private val database: VeilDatabase = VeilDatabase.get(context),
    private val limits: MangaCbzImportLimits = MangaCbzImportLimits(),
    private val clock: () -> Long = System::currentTimeMillis
) {
    private val appContext = context.applicationContext
    private val ingestor = MangaCbzIngestor(limits = limits, clock = clock)
    private val offlineStore = RoomMangaOfflineCacheIndex(database)

    fun supports(uri: Uri): Boolean {
        val name = displayName(uri)?.lowercase(Locale.ROOT).orEmpty()
        if (name.endsWith(".cbz")) return true
        return appContext.contentResolver.getType(uri)
            ?.lowercase(Locale.ROOT)
            .let { type ->
                type == MIME_CBZ ||
                    type == MIME_CBZ_ALT
            }
    }

    suspend fun importCbz(uri: Uri): BookImportResult {
        val materialized = materialize(uri)
        val sourceFile = materialized.file
        var committedBook: Book? = null

        try {
            val book = Book(
                id = UUID.randomUUID().toString(),
                title = materialized.displayName
                    .substringBeforeLast('.')
                    .trim()
                    .ifEmpty { "Untitled comic" },
                author = "",
                progress = 0f,
                currentChapter = "",
                totalPages = 0,
                pagesRead = 0,
                format = BookFormat.COMIC,
                sourceUri = Uri.fromFile(sourceFile).toString(),
                mediaType = MIME_CBZ,
                addedAtEpochMs = clock(),
                lastOpenedAtEpochMs = 0L,
                favorite = false,
                // Empty is the existing terminal sentinel for "no publication cover".
                // CBZ thumbnails will be generated by the Manga pipeline rather than Readium.
                coverCachePath = "",
                contentFingerprint = materialized.sha256
            )

            val commit = library.addImportedBook(book)
            if (commit.duplicate) {
                return commit
            }
            committedBook = commit.book

            val mangaId = CanonicalMangaId(commit.book.id)
            val chapterAnchor = MangaChapterAnchor(
                normalizedTitle = commit.book.title,
                providerChapterKeyHint = materialized.sha256
            )
            val offlineId = requireNotNull(
                MangaOfflineChapterLocator.idFor(mangaId, chapterAnchor)
            ) { "Local CBZ chapter could not produce a durable offline identity" }
            val cacheKey = MangaCacheLayout.chapterDirectory(offlineId)
            val chapterId = UUID.nameUUIDFromBytes(
                ("veil-manga-chapter:" + commit.book.id + ":" + cacheKey)
                    .toByteArray(Charsets.UTF_8)
            ).toString()
            val sourceId = MangaCbzIngestor.LOCAL_CBZ_SOURCE_ID
            val mangaKey = commit.book.id
            val chapterKey = materialized.sha256

            database.withTransaction {
                database.mangaCatalog().upsertSourceLink(
                    MangaSourceLinkEntity(
                        bookId = commit.book.id,
                        sourceId = sourceId.value,
                        mangaKey = mangaKey,
                        publicUrl = null
                    )
                )
                database.mangaCatalog().upsertChapter(
                    MangaChapterEntity(
                        id = chapterId,
                        bookId = commit.book.id,
                        readingOrder = 0,
                        cacheKey = cacheKey,
                        title = commit.book.title,
                        normalizedTitle = commit.book.title,
                        volume = null,
                        number = null,
                        languageTag = null
                    )
                )
                database.mangaCatalog().upsertChapterSource(
                    MangaChapterSourceEntity(
                        chapterId = chapterId,
                        bookId = commit.book.id,
                        sourceId = sourceId.value,
                        mangaKey = mangaKey,
                        chapterKey = chapterKey
                    )
                )
            }

            val result = withContext(Dispatchers.IO) {
                ingestor.ingest(
                    archiveFile = sourceFile,
                    cacheRoot = cacheRoot(appContext),
                    chapterId = offlineId,
                    anchor = chapterAnchor,
                    originChapterKey = chapterKey,
                    originSourceId = sourceId
                )
            }
            val manifest = when (result) {
                is MangaCbzImportResult.Success -> result.manifest
                is MangaCbzImportResult.Failure -> {
                    throw LocalMangaImportException(
                        "CBZ ingestion failed: " + result.reason.name
                    )
                }
            }
            offlineStore.put(manifest)
            return commit
        } catch (cancelled: CancellationException) {
            committedBook?.let { rollback(it) }
            throw cancelled
        } catch (error: Throwable) {
            committedBook?.let { rollback(it) }
            if (committedBook == null) {
                withContext(Dispatchers.IO) {
                    sourceFile.takeIf(File::exists)?.delete()
                }
            }
            throw error
        }
    }

    private suspend fun rollback(book: Book) {
        val mangaId = CanonicalMangaId(book.id)
        val chapters = database.mangaCatalog().listChapters(book.id)
        withContext(Dispatchers.IO) {
            chapters.forEach { chapter ->
                val directory = File(cacheRoot(appContext), chapter.cacheKey)
                deleteConfinedDirectory(cacheRoot(appContext), directory)
            }
        }
        library.rollbackImportedBook(book)
        // The Book delete owns all Room cascades. This explicit progress delete is defensive for
        // in-memory/test databases where foreign-key enforcement may be configured differently.
        database.mangaProgress().delete(mangaId.value)
    }

    private suspend fun materialize(uri: Uri): MaterializedCbz = withContext(Dispatchers.IO) {
        val importsDir = File(appContext.filesDir, "publications").apply { mkdirs() }
        val displayName = displayName(uri)
            ?.takeIf(String::isNotBlank)
            ?: "local-manga.cbz"
        val declaredSize = querySize(uri)
        if (declaredSize != null && declaredSize > limits.maxArchiveBytes) {
            throw LocalMangaImportException("CBZ archive exceeds the configured import limit")
        }

        val target = File(importsDir, UUID.randomUUID().toString() + ".cbz")
        val partial = File(importsDir, target.name + ".partial")
        val digest = MessageDigest.getInstance("SHA-256")
        var copied = 0L

        try {
            appContext.contentResolver.openInputStream(uri)?.use { input ->
                partial.outputStream().buffered().use { output ->
                    val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                    while (true) {
                        val read = input.read(buffer)
                        if (read < 0) break
                        if (read == 0) continue
                        copied += read
                        if (copied > limits.maxArchiveBytes) {
                            throw LocalMangaImportException(
                                "CBZ archive exceeds the configured import limit"
                            )
                        }
                        digest.update(buffer, 0, read)
                        output.write(buffer, 0, read)
                    }
                }
            } ?: throw LocalMangaImportException("Android could not read the selected CBZ file")

            if (copied <= 0L) {
                throw LocalMangaImportException("The selected CBZ file is empty")
            }
            if (!partial.renameTo(target)) {
                throw LocalMangaImportException("Could not commit the local CBZ copy")
            }
            MaterializedCbz(
                file = target,
                displayName = displayName,
                sha256 = digest.digest().toHex()
            )
        } catch (error: Throwable) {
            partial.delete()
            target.delete()
            throw error
        }
    }

    private fun displayName(uri: Uri): String? {
        if (uri.scheme == "file") return uri.lastPathSegment
        return runCatching {
            appContext.contentResolver.query(
                uri,
                arrayOf(OpenableColumns.DISPLAY_NAME),
                null,
                null,
                null
            )?.use { cursor ->
                if (!cursor.moveToFirst()) return@use null
                cursor.getString(cursor.getColumnIndexOrThrow(OpenableColumns.DISPLAY_NAME))
            }
        }.getOrNull()
    }

    private fun querySize(uri: Uri): Long? = runCatching {
        appContext.contentResolver.query(
            uri,
            arrayOf(OpenableColumns.SIZE),
            null,
            null,
            null
        )?.use { cursor ->
            if (!cursor.moveToFirst()) return@use null
            val index = cursor.getColumnIndex(OpenableColumns.SIZE)
            if (index < 0 || cursor.isNull(index)) null else cursor.getLong(index)
        }
    }.getOrNull()

    private fun deleteConfinedDirectory(root: File, candidate: File) {
        runCatching {
            val canonicalRoot = root.canonicalFile
            val canonicalCandidate = candidate.canonicalFile
            if (
                canonicalCandidate != canonicalRoot &&
                canonicalCandidate.toPath().startsWith(canonicalRoot.toPath())
            ) {
                canonicalCandidate.deleteRecursively()
            }
        }
    }

    private data class MaterializedCbz(
        val file: File,
        val displayName: String,
        val sha256: String
    )

    companion object {
        const val MIME_CBZ = "application/vnd.comicbook+zip"
        const val MIME_CBZ_ALT = "application/x-cbz"

        fun cacheRoot(context: Context): File =
            File(context.applicationContext.filesDir, "manga-cache")
    }
}

class LocalMangaImportException(message: String) : IOException(message)

private fun ByteArray.toHex(): String = joinToString(separator = "") { byte ->
    "%02x".format(Locale.ROOT, byte.toInt() and 0xff)
}
